apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "go-echo098521ff-052f-41a7-ba5f-f9778ecd2f3b.fullname" . }}-config
  labels:
    {{- include "go-echo098521ff-052f-41a7-ba5f-f9778ecd2f3b.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
data:
{{- range $key, $value := .Values.envVars }}
  {{ $key }}: {{ $value }}
{{- end }}
