apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "go-echodfc16b6e-95e7-4968-ab7d-62bd73f800b1.fullname" . }}-config
  labels:
    {{- include "go-echodfc16b6e-95e7-4968-ab7d-62bd73f800b1.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
data:
{{- range $key, $value := .Values.envVars }}
  {{ $key }}: {{ $value }}
{{- end }}
