apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-echo36706037-c1d3-437d-b9af-ce05f949f715.fullname" . }}
  labels:
    {{- include "go-echo36706037-c1d3-437d-b9af-ce05f949f715.labels" . | nindent 4 }}
  annotations:
    {{ toYaml .Values.service.annotations | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: svchttp
  selector:
    {{- include "go-echo36706037-c1d3-437d-b9af-ce05f949f715.selectorLabels" . | nindent 6 }}
