apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-echo8a024629-015e-47a8-b134-ab0fc450593a.fullname" . }}
  labels:
    {{- include "go-echo8a024629-015e-47a8-b134-ab0fc450593a.labels" . | nindent 4 }}
    kubernetes.azure.com/generator: {{.Values.generatorLabel}}
  annotations:
    {{ toYaml .Values.service.annotations | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: svchttp
  selector:
    {{- include "go-echo8a024629-015e-47a8-b134-ab0fc450593a.selectorLabels" . | nindent 6 }}
