apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-echo8b48f0d8-1382-44e7-a1ad-99a9e2ca2708.fullname" . }}
  labels:
    {{- include "go-echo8b48f0d8-1382-44e7-a1ad-99a9e2ca2708.labels" . | nindent 4 }}
  annotations:
    {{ toYaml .Values.service.annotations | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: svchttp
  selector:
    {{- include "go-echo8b48f0d8-1382-44e7-a1ad-99a9e2ca2708.selectorLabels" . | nindent 6 }}
